#!/bin/bash

in=~/.vimsedin
out=~/.vimsedout
cmd=~/.vimsedcmd.vim

normal=$(echo "gg0$1")
command="normal $normal\nwrite! $out\nquit!"

cat > $in \
    && echo -e $command > $cmd \
    && vim -e -s -c "so $cmd" $in \
    && cat $out \
    && rm $in $out $cmd

