#!/bin/sh

in=~/vimsedin
out=~/vimsedout
cmd=~/vimsedcmd

normal=$(echo "gg0$1" | sed s///)
command="normal $normal\nwrite! $out"

cat > $in \
    && echo $command > $cmd \
    && vim -e -s $in < $cmd \
    && cat $out \
    && rm ~/vimsed{in,cmd,out}
